hub:
  # output of first execution of 'openssl rand -hex 32'
  cookieSecret: "RANDOM_STRING"
token:
  # output of first execution of 'openssl rand -hex 32'
  proxy: "RANDOM_STRING"
# singleuser:
#   image:
#      name: ipython/ipython-in-depth
#      tag: pycon2017-0.1
